version: "3"
services:
  fuocstats:
    image: fuocnetwork/ethstats
    container_name: ethstats
    environment:
      - PORT=3000
      - WS_SECRET=secret
    network_mode: "host"
    restart: always

